<?php
  include('cabecera.php');
  $title='Bienvenido ' .$_SESSION['nombre'] .' ' .$_SESSION['paterno'];
  include('titulo.php');
  include('menu_admin.php');

  switch($op){
    case 0: include('admin/horario_a.php');
    break;
    case 1: include('admin/materia.php');
    break;
    case 2: include('admin/aulas.php');
    break;
    case 5: include('admin/asesores.php');
    break;
    case 7: include('admin/tutores.php');
    break;
    case 8: include('admin/periodos.php');
    break;
    case 9: include('admin/admin.php');
    break;
    case 10: include('admin/salir.php');
    break;
    case 20: include('agregaasesor.php');
    break;
    case 50: echo('<script>alert("Error! Usuario repetido o faltan datos")</script>');
    include('admin/asesores.php');
    break;
    case 51: echo('<script>alert("Error! Asegurate que no queden circulos en esta aula")</script>');
    include('admin/aulas.php');
    break;
    case 52: echo('<script>alert("Error! Asegurate que no queden circulos con estas materias")</script>');
    include('admin/materia.php');
    break;
    case 53: echo('<script>alert("Error! Usuario repetido o faltan datos")</script>');
    include('admin/tutores.php');
    break;
    case 54: echo('<script>alert("Error! Asegurate de no tener circulos con este alumno")</script>');
    include('admin/tutores.php');
    break;
    case 55: echo('<script>alert("Error! Asegurate de tener todos los datos correctos")</script>');
    include('admin/asesor_mod.php');
    break;
    case 56: echo('<script>alert("Error! Asegurate de tener todos los datos correctos")</script>');
    include('admin/tutor_mod.php');
    break;
    case 100: include('admin/horario_mod.php');
    break;
    case 101: include('admin/materia_mod.php');
    break;
    case 102: include('admin/aula_mod.php');
    break;
    case 103: include('admin/asesor_mod.php');
    break;
    case 104: include('admin/tutor_mod.php');
    break;
    case 110: include('admin/asistencias_a.php');
    break;
    case 111:include('admin/horario_id_a.php');
    break;
    case 112:echo('<script>alert("Ya se registro una asistencia hoy!")</script>');
    include('admin/horario_a.php');
    break;
    case 113:echo('<script>alert("Dato vacio o incorrecto")</script>');
    include('admin/materia.php');
    break;
    case 114:echo('<script>alert("Dato vacio o incorrecto")</script>');
    include('admin/aulas.php');
    break;
    case 115:echo('<script>alert("Error! Datos vacio o incorrectos")</script>');
    include('admin/horario_a.php');
    break;
    case 120:include('admin/admin_mod.php');
    break;
    case 121:echo('<script>alert("Aula no disponible o usuario ya ocupado en ese horario")</script>');
    include('admin/horario_a.php');
    break;
    case 122:echo('<script>alert("Circulo registrado")</script>');
    include('admin/horario_a.php');
    break;
    case 123:echo('<script>alert("Circulo actualizado correctamente")</script>');
    include('admin/horario_a.php');
    break;
    case 124:echo('<script>alert("Dato vacio")</script>');
    include('admin/admin.php');
    break;
    case 125:echo('<script>alert("Error! Borra antes los circulos y los tutores de este periodo")</script>');
    include('admin/periodos.php');
    break;
  }
 ?>
